import bs58 from "bs58";
import { execSync } from "child_process";
import { type Request, type Response } from 'express';
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { BN254_MODULUS, EMPTY_TREE_ZEROS, TREE_DEPTH, VERIFIER_DIR } from "./constant";

function pubkeyToField(pubkeyBase58: string): string {
  const bytes = bs58.decode(pubkeyBase58);
  if (bytes.length !== 32) {
    throw new Error(`Invalid pubkey length: expected 32 bytes, got ${bytes.length}`);
  }
  // Take first 31 bytes to fit within BN254 field modulus
  const truncatedBytes = bytes.slice(0, 31);
  const hex = Buffer.from(truncatedBytes).toString("hex");
  const value = BigInt("0x" + hex);
  if (value >= BN254_MODULUS) {
    throw new Error("Pubkey conversion resulted in value outside field");
  }
  return value.toString();
}

function getMerkleProof(leafIndex: number): { proof: string[]; isEven: boolean[]; } {
  const proof: string[] = [];
  const isEven: boolean[] = [];

  let idx = leafIndex;
  for (let i = 0; i < TREE_DEPTH; i++) {
    // At each level, sibling is an empty subtree (zeros[i])
    proof.push(EMPTY_TREE_ZEROS[i]);
    // is_even = true means leaf is on left (even index at this level)
    isEven.push((idx & 1) === 0);
    idx = idx >> 1;
  }
  return { proof, isEven };
}

function writeProverToml(nullifier: string, secret: string, amount: string, nullifierHash: string,
  recipient: string, merkleRoot: string, merkleProof: string[], isEven: boolean[]): void {
  const toml = `# Generated by backend API\n# Public Inputs\nroot = "${merkleRoot}"
nullifier_hash = "${nullifierHash}"\nrecipient = "${recipient}"\namount = "${amount}"
# Private Inputs\nnullifier = "${nullifier}"\nsecret = "${secret}"\nmerkle_proof = [
    ${merkleProof.map((p) => `"${p}"`).join(",\n    ")}\n]\nis_even = [${isEven.join(", ")}]\n`;
  writeFileSync(path.join(VERIFIER_DIR, "Prover.toml"), toml);
}

function generateProof(): { proof: Buffer, publicWitness: Buffer } {
  execSync("nargo execute", { cwd: VERIFIER_DIR, stdio: "pipe" });
  execSync("sunspot prove target/verifier.json target/verifier.gz target/verifier.ccs target/verifier.pk",
    { cwd: VERIFIER_DIR, stdio: "pipe" });
  const proof = readFileSync(path.join(VERIFIER_DIR, "target/verifier.proof"));
  const publicWitness = readFileSync(path.join(VERIFIER_DIR, "target/verifier.pw"));
  return { proof, publicWitness };
}

export async function withdraw(req: Request, res: Response) {
  try {
    const { depositNote, recipient } = req.body;
    if (!depositNote) {
      return res.status(400).json({ error: "Missing depositNote" });
    }
    if (!recipient) {
      return res.status(400).json({ error: "Missing recipient address" });
    }
    const requiredFields =
      ["nullifier", "secret", "amount", "commitment", "nullifierHash", "merkleRoot", "leafIndex"];
    for (const field of requiredFields) {
      if (depositNote[field] === undefined) {
        return res.status(400).json({ error: `Invalid depositNote: missing ${field}` });
      }
    }
    try {
      const decoded = bs58.decode(recipient);
      if (decoded.length !== 32) {
        return res.status(400).json({ error: "Invalid recipient: must be a 32-byte Solana address" });
      }
    } catch {
      return res.status(400).json({ error: "Invalid recipient: not valid base58" });
    }
    const leafIndex = Number(depositNote.leafIndex);
    console.log(`Generating withdrawal proof for recipient ${recipient} at leaf index ${leafIndex}...`);
    const recipientField = pubkeyToField(recipient);
    const { proof: merkleProof, isEven } = getMerkleProof(leafIndex);
    writeProverToml(
      depositNote.nullifier, depositNote.secret, depositNote.amount, depositNote.nullifierHash,
      recipientField, depositNote.merkleRoot, merkleProof, isEven
    );

    console.log("Generating ZK proof...");
    const { proof, publicWitness } = generateProof();
    console.log(`Proof generated: ${proof.length} bytes`);

    const withdrawalProof = {
      proof: Array.from(proof),
      publicWitness: Array.from(publicWitness),
      nullifierHash: depositNote.nullifierHash,
      merkleRoot: depositNote.merkleRoot,
      recipient: recipient,
      amount: depositNote.amount,
    };
    res.json({ withdrawalProof });
  } catch (error) {
    console.error("Withdrawal proof generation error:", error);
    res.status(500).json({ error: error instanceof Error ? error.message : "Unknown error" });
  }
}
