[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "CBm7pwVU1tcwBgWtHyJaEF5qeJkns6iQSvL2A6wkcrxo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
