[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "4W88mTBdwLUv3RsheJGJhpTp1Vm6CEGvWyYsA2c8KWvt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
